/* routers constants */
export const ADMIN_ROUTE = '/admin';
export const MAIN_ROUTE = '/';
export const CARDIGANS_ROUTE = '/cardigans';
export const CATALOG_ROUTE = '/catalog';
export const DRESSES_ROUTE = '/dresses';
export const SHORTS_ROUTE = '/shorts';
export const SUITS_ROUTE = '/suits';
export const TROUSERS_ROUTE = '/trousers';

/* admin routers constants */
export const ADMIN_DASHBOARD_ROUTE = '/dashboard';
export const ADMIN_CATALOG_ROUTE = '/catalog';
export const ADMIN_CATEGORIES_ROUTE = '/catalog/categories';
export const ADMIN_PRODUCTS_ROUTE = '/catalog/products';
export const ADMIN_FILTERS_ROUTE = '/catalog/filters';
export const ADMIN_ATTRIBUTES_ROUTE = '/catalog/attributes';
export const ADMIN_MAKERS_ROUTE = '/catalog/makers';
export const ADMIN_DOWNLOADS_ROUTE = '/catalog/downloads';
export const ADMIN_REVIEWS_ROUTE = '/catalog/reviews';
export const ADMIN_ARTICLES_ROUTE = '/catalog/articles';
export const ADMIN_SALES_ROUTE = '/sales';
export const ADMIN_ORDERS_ROUTE = '/sales/orders';
export const ADMIN_RETURNS_ROUTE = '/sales/returns';
export const ADMIN_CLIENTS_ROUTE = '/clients';
export const ADMIN_CLIENTS_LIST_ROUTE = '/clients/list';
export const ADMIN_CLIENTS_GROUPS_ROUTE = '/clients/groups';
export const ADMIN_DELIVERY_ROUTE = '/delivery';
export const ADMIN_NOVAPOSHTA_ROUTE = '/delivery/nova-poshta';
export const ADMIN_SYSTEM_ROUTE = '/system';
export const ADMIN_SETTINGS_ROUTE = '/system/settings';
export const ADMIN_LOCALIZATION_ROUTE = '/clients/localization';
